### ISSUE TITLE
not tested on windows... 

### ISSUE THREAD

**Issue by andersfi** [GBIF-Europe/darwinator#1]
this package has not been tested on windows

**Comment by mskyttner** [comment]
Will try to test using Windows VMs inside VirtualBox... there seem to be some download links here:
- [VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
- [Windows 10](https://www.microsoft.com/en-us/software-download/windows10ISO)
But I am out of disk space currently!

**Comment by mskyttner** [comment]
Still no disk space for Windows on my laptop but the package is now checked with `devtools::check()` which does [these checks: ](http://r-pkgs.had.co.nz/check.html)... 

So anyone with a Windows can try this to see that things works as expected with the download ... which involves tempfiles:

``` r
devtools::install_github("GBIF-Europe/darwinator@v0.1.1")
library(darwinator)
x <- sampling_event_data(dataset_key_from_gbif)
```

Then please proceed to validate that the package is able to retrieve Norwegian sampling data event datasets correctly...

**Comment by mskyttner** [comment]
Tested on Windows 7 - download of example dataset works.
